#!/usr/bin/env bash
# desc: Pin the images to a previous version (and optionally restore data)
set -euo pipefail
_here="${BASH_SOURCE[0]%/*}/.."
# shellcheck source=../lib/config.sh
. "$_here/lib/config.sh"
# shellcheck source=../lib/alert.sh
. "$_here/lib/alert.sh"
# shellcheck source=../lib/compose.sh
. "$_here/lib/compose.sh"

usage() {
  cat <<'USAGE'
Usage: gymme rollback <tag> [--with-data ARCHIVE] [--dry-run] [--yes]
       gymme rollback --clear [--yes]

Pins the api and web images to an earlier published tag by writing docker-compose.override.yml, then pulls, restarts and
waits for health. Tags: X.Y.Z (a release) or sha-<short commit> (any merge to main). Your data is not touched unless you
pass --with-data (use it only when a release corrupted data: it runs `gymme restore`, which keeps the current data as
data.broken.*).

  --clear           remove the pin and go back to the latest images
  --with-data FILE  also restore this backup archive first
  --dry-run         show the plan, change nothing
  --yes, -y         do not ask for confirmation
  -h, --help        this help

While a pin is active `gymme update` refuses to run: clear the pin first.
USAGE
}

TAG='' CLEAR=0 DRY_RUN=0 DATA_ARCHIVE=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --clear) CLEAR=1 ;;
    --dry-run) DRY_RUN=1 ;;
    -y | --yes) ASSUME_YES=1 ;;
    --with-data)
      shift
      DATA_ARCHIVE="${1:-}"
      [ -n "$DATA_ARCHIVE" ] || die_usage "--with-data needs an archive"
      ;;
    -h | --help) usage; exit 0 ;;
    -*) usage >&2; die_usage "unknown option '$1'" ;;
    *)
      [ -z "$TAG" ] || die_usage "only one tag can be given"
      TAG="$1"
      ;;
  esac
  shift
done
export ASSUME_YES="${ASSUME_YES:-0}"

load_config
secure_umask
OVERRIDE="$GYMME_ROOT/docker-compose.override.yml"
MARKER="# generated by gymme rollback"
STATE="$GYMME_ROOT/.gymme-state"

ours() { [ -f "$OVERRIDE" ] && [ "$(head -n 1 "$OVERRIDE")" = "$MARKER" ]; }
refuse_foreign() {
  if [ -f "$OVERRIDE" ] && ! ours; then
    die "a docker-compose.override.yml that gymme did not create already exists; not touching it. Merge the image tags by hand."
  fi
}

if [ "$CLEAR" = 1 ]; then
  [ -z "$TAG" ] || die_usage "--clear does not take a tag"
  refuse_foreign
  if ! ours; then
    ok "nothing is pinned"
    exit 0
  fi
  [ "$DRY_RUN" = 1 ] && { info "dry-run: would remove the pin and restart on the latest images"; exit 0; }
  confirm "Remove the version pin and use the latest images?" || die "aborted. Nothing was changed."
  rm -f "$OVERRIDE" "$STATE/pinned"
  if daemon_up; then
    compose_cmd pull >/dev/null 2>&1 || warn "could not pull the latest images; restarting with what is available"
    compose_cmd up -d >/dev/null 2>&1 || die "docker compose up failed. See: gymme logs"
    wait_health "$BASE_URL/api/health" 120 || die "the API does not answer at $BASE_URL. Check: gymme logs api --errors"
  else
    warn "Docker is not running: the pin is removed; start with: gymme start"
    exit 0
  fi
  ok "pin removed: running the latest images"
  exit 0
fi

if [ -z "$TAG" ]; then
  usage >&2
  if [ -d "$GYMME_ROOT/.git" ] && command -v git >/dev/null 2>&1; then
    tags="$(git -C "$GYMME_ROOT" tag --sort=-v:refname 2>/dev/null | head -n 5 | paste -sd' ' - || true)"
    [ -n "$tags" ] && info "Recent releases: $tags"
  fi
  die_usage "missing tag"
fi

TAG="${TAG#v}"
if ! printf '%s' "$TAG" | grep -Eq '^([0-9]+\.[0-9]+\.[0-9]+|sha-[0-9a-f]{7,40})$'; then
  die_usage "tag must look like 1.4.0 or sha-abc1234 (got '$TAG')"
fi

refuse_foreign
COMPOSE_FILE="$GYMME_ROOT/docker-compose.yml"
[ -f "$COMPOSE_FILE" ] || die "docker-compose.yml not found in $GYMME_ROOT"
API_IMG="$(sed -n 's/^ *image: *\([^: ]*gym[a-z]*-api\).*$/\1/p' "$COMPOSE_FILE" | head -n 1)"
WEB_IMG="$(sed -n 's/^ *image: *\([^: ]*gym[a-z]*-web\).*$/\1/p' "$COMPOSE_FILE" | head -n 1)"
[ -n "$API_IMG" ] && [ -n "$WEB_IMG" ] || die "could not find the api and web images in docker-compose.yml"
daemon_up || die "Docker is not running. Start Docker, then run: gymme rollback $TAG"

if [ "$DRY_RUN" = 1 ]; then
  [ -n "$DATA_ARCHIVE" ] && info "dry-run: would restore $DATA_ARCHIVE first"
  info "dry-run: would pin $API_IMG:$TAG and $WEB_IMG:$TAG, pull, restart and wait for health"
  exit 0
fi
info "Pinning Gymme to $TAG${DATA_ARCHIVE:+ and restoring $(basename "$DATA_ARCHIVE")}."
confirm "Continue?" || die "aborted. Nothing was changed."

if [ -n "$DATA_ARCHIVE" ]; then
  "${BASH:-bash}" "${BASH_SOURCE[0]%/*}/../user/restore.sh" "$DATA_ARCHIVE" --yes --no-start || die "the data restore failed; nothing was pinned."
fi

PREVIOUS=''
ours && PREVIOUS="$(cat "$OVERRIDE")"
cat >"$OVERRIDE" <<YAML
$MARKER
# Remove with: gymme rollback --clear
services:
  api:
    image: $API_IMG:$TAG
  web:
    image: $WEB_IMG:$TAG
YAML

if ! compose_cmd pull >/dev/null 2>&1; then
  if [ -n "$PREVIOUS" ]; then printf '%s\n' "$PREVIOUS" >"$OVERRIDE"; else rm -f "$OVERRIDE"; fi
  die "could not pull tag $TAG (does it exist? published tags look like 1.4.0 or sha-abc1234). The previous setup was kept."
fi
compose_cmd up -d >/dev/null 2>&1 || die "docker compose up failed. To undo: gymme rollback --clear"
(umask 077 && mkdir -p "$STATE" && printf '%s\n' "$TAG" >"$STATE/pinned")
if ! wait_health "$BASE_URL/api/health" 120; then
  alert crit rollback-health "Gymme rollback: API not answering" "Pinned to $TAG but $BASE_URL/api/health does not answer."
  die "pinned to $TAG but the API does not answer at $BASE_URL. Check: gymme logs api --errors. To undo: gymme rollback --clear"
fi
ok "Gymme is pinned to $TAG. 'gymme update' is blocked until: gymme rollback --clear"
