#!/usr/bin/env bash
set -u
# shellcheck source=helpers.sh
. "$(dirname "$0")/helpers.sh"
OG="$REPO_ROOT/scripts/opengym"
export WAIT_SLEEP=0
export OPENGYM_QUIET=0
MARK="# generated by opengym rollback"

setup() {
  new_sandbox
  use_fixture data_ok
  cp "$REPO_ROOT/docker-compose.yml" "$SB/docker-compose.yml"
  printf 'RP_ID=localhost\nORIGIN=http://localhost:8080\n' >"$SB/.env"
  export LOG_FILE="$SB/logs/opengym.log" MOCK_OUT_CURL='{"ok":true,"users":2}'
}
OV() { echo "$SB/docker-compose.override.yml"; }

# ---------- pin
setup
assert_exit 0 "rollback to a release" -- "$OG" rollback 1.4.0 --yes
assert_eq "$MARK" "$(head -n 1 "$(OV)")" "override carries the marker"
assert_contains "ghcr.io/duartesantos8/opengym-api:1.4.0" "$(cat "$(OV)")" "api image pinned"
assert_contains "ghcr.io/duartesantos8/opengym-web:1.4.0" "$(cat "$(OV)")" "web image pinned"
log="$(cat "$MOCK_LOG")"
assert_contains "compose pull" "$log" "pulls the pinned images"
assert_contains "compose up -d" "$log" "restarts"
assert_contains "api/health" "$log" "checks health"
assert_eq "1.4.0" "$(cat "$SB/.opengym-state/pinned")" "pinned tag recorded"
assert_contains "--clear" "$T_OUT" "tells how to undo"
assert_eq 0 "$(mock_calls 'compose down')" "data is not touched: no stop"

setup
assert_exit 0 "sha tag" -- "$OG" rollback sha-abc1234 --yes
assert_contains ":sha-abc1234" "$(cat "$(OV)")" "sha tag pinned"
setup
assert_exit 0 "v prefix is normalised" -- "$OG" rollback v1.4.0 --yes
assert_contains ":1.4.0" "$(cat "$(OV)")" "v stripped"
for bad in latest 1.4 ../x "1.4.0;rm" sha-xyz "" ; do
  setup
  assert_exit 2 "rejects tag '$bad'" -- "$OG" rollback "$bad" --yes
  assert_no_file "$(OV)" "no override for a bad tag"
done

# ---------- safety
setup; printf 'services: {}\n' >"$(OV)"
assert_exit 1 "foreign override is never touched" -- "$OG" rollback 1.4.0 --yes
assert_eq "services: {}" "$(cat "$(OV)")" "foreign override unchanged"
assert_eq 0 "$(mock_calls 'compose pull')" "nothing pulled"
setup
assert_exit 1 "pull failure" -- env MOCK_EXIT_DOCKER_COMPOSE_PULL=1 "$OG" rollback 9.9.9 --yes
assert_no_file "$(OV)" "failed pull leaves no override behind"
assert_contains "9.9.9" "$T_OUT" "names the tag"
setup
"$OG" rollback 1.4.0 --yes >/dev/null 2>&1; before="$(cat "$(OV)")"
assert_exit 1 "pull failure with an existing pin" -- env MOCK_EXIT_DOCKER_COMPOSE_PULL=1 "$OG" rollback 9.9.9 --yes
assert_eq "$before" "$(cat "$(OV)")" "previous pin restored"
setup
assert_exit 1 "health failure" -- env MOCK_EXIT_CURL=22 "$OG" rollback 1.4.0 --yes
assert_file "$(OV)" "pin stays so you can inspect"
assert_contains "rollback --clear" "$T_OUT" "tells how to undo"
setup
assert_exit 0 "dry run" -- "$OG" rollback 1.4.0 --dry-run
assert_no_file "$(OV)" "dry run writes nothing"
assert_eq 0 "$(mock_calls 'compose pull')" "dry run pulls nothing"
assert_contains "would" "$T_OUT" "dry run explains"
assert_exit 1 "no TTY and no --yes aborts" -- "$OG" rollback 1.4.0
assert_no_file "$(OV)" "abort writes nothing"
assert_exit 1 "docker down" -- env MOCK_EXIT_DOCKER_INFO=1 "$OG" rollback 1.4.0 --yes
rm "$SB/docker-compose.yml"
assert_exit 1 "no docker-compose.yml" -- "$OG" rollback 1.4.0 --yes

# ---------- clear
setup
"$OG" rollback 1.4.0 --yes >/dev/null 2>&1; : >"$MOCK_LOG"
assert_exit 0 "clear the pin" -- "$OG" rollback --clear --yes
assert_no_file "$(OV)" "override removed"
assert_no_file "$SB/.opengym-state/pinned" "pin record removed"
assert_contains "compose up -d" "$(cat "$MOCK_LOG")" "restarts on latest"
assert_exit 0 "clearing twice" -- "$OG" rollback --clear --yes
assert_contains "nothing is pinned" "$T_OUT" "says nothing is pinned"
setup; printf 'services: {}\n' >"$(OV)"
assert_exit 1 "clear refuses a foreign override" -- "$OG" rollback --clear --yes
assert_file "$(OV)" "foreign override kept"
assert_exit 2 "--clear with a tag" -- "$OG" rollback --clear 1.4.0

# ---------- with data
setup
printf 'secret' >"$SB/data/secret"
A="$("$OG" backup --no-consistent --quiet 2>/dev/null | tail -1)"
orig="$(cat "$SB/data/db.json")"
cp "$TESTS_DIR/fixtures/data_corrupt_db/db.json" "$SB/data/db.json"
: >"$MOCK_LOG"
assert_exit 0 "rollback with data" -- "$OG" rollback 1.4.0 --with-data "$A" --yes
assert_eq "$orig" "$(cat "$SB/data/db.json")" "data restored from the archive"
assert_file "$(OV)" "and the images are pinned"
assert_contains "compose down" "$(cat "$MOCK_LOG")" "restore stopped the stack"
setup
assert_exit 1 "missing archive" -- "$OG" rollback 1.4.0 --with-data "$SB/none.tgz" --yes
assert_no_file "$(OV)" "nothing pinned when the restore fails"
assert_exit 2 "--with-data needs a value" -- "$OG" rollback 1.4.0 --with-data

# ---------- update refuses while pinned
setup
"$OG" rollback 1.4.0 --yes >/dev/null 2>&1; : >"$MOCK_LOG"
assert_exit 1 "update refuses while pinned" -- "$OG" update --yes
assert_contains "rollback --clear" "$T_OUT" "tells to clear the pin"
assert_eq 0 "$(mock_calls 'compose pull')" "update did nothing"

# ---------- usage
setup
assert_exit 2 "tag required" -- "$OG" rollback
assert_contains "Usage" "$T_OUT" "prints usage"
assert_exit 2 "unknown option" -- "$OG" rollback --bogus
assert_exit 0 "--help" -- "$OG" rollback --help

t_summary
